# Name- Sayan Paul 
Scholar number -222115107

# Asignment number -1
Asignment date- 06/01/2023

In [87]:
import pandas as pd
import numpy as np

In [88]:
import random 

In [89]:
from sklearn.neighbors import NearestNeighbors

In [90]:
a = np.random.randint(0,50,size=500)

In [91]:
a

array([25, 20, 10, 24, 38,  3, 16, 42, 40, 36, 45,  7,  3, 41,  5, 11, 30,
       28, 35, 28, 23, 30, 18, 42,  5, 22, 27, 23, 28, 29, 13, 22,  9, 45,
       47, 25, 26, 43, 39, 43, 26, 10, 42, 15, 40, 34,  4, 46,  9, 34, 16,
       34, 33,  5, 46, 44, 47, 14,  3,  9, 17, 32, 15,  7,  5, 30, 25,  4,
       25, 44, 49, 47, 10, 26, 12, 48, 36, 49,  1, 21, 13, 24, 15, 18, 38,
       27, 33, 36, 36, 24, 43, 29,  4, 20, 49,  5, 36, 13, 12, 18, 14,  2,
        9, 29, 44, 21, 41, 20, 15, 33, 17, 47, 19, 14, 20, 13, 25, 41, 11,
        7,  8, 27, 16, 26,  4, 18,  6, 13, 45,  9, 29, 17, 34,  3, 42,  0,
        4, 24, 30, 49, 23, 15, 34,  8, 40, 22,  0,  5, 46, 42, 28, 19, 13,
       10, 25, 32, 19, 45,  0,  5, 11, 33, 20,  2, 28, 13,  2, 48, 14, 32,
       22,  6, 10, 28, 40, 42, 36,  2,  7, 30,  9, 22, 12, 49, 29, 12, 47,
       20, 23, 35, 13,  9, 40, 28, 14, 36, 24, 15,  7,  7, 16, 33,  3, 45,
       31, 29, 25, 13, 40, 23, 11, 33,  2, 12, 34, 33, 39, 17,  9, 25, 40,
       21, 12, 40,  2, 14

In [92]:
b=a.reshape(250,2)

In [93]:
b

array([[25, 20],
       [10, 24],
       [38,  3],
       [16, 42],
       [40, 36],
       [45,  7],
       [ 3, 41],
       [ 5, 11],
       [30, 28],
       [35, 28],
       [23, 30],
       [18, 42],
       [ 5, 22],
       [27, 23],
       [28, 29],
       [13, 22],
       [ 9, 45],
       [47, 25],
       [26, 43],
       [39, 43],
       [26, 10],
       [42, 15],
       [40, 34],
       [ 4, 46],
       [ 9, 34],
       [16, 34],
       [33,  5],
       [46, 44],
       [47, 14],
       [ 3,  9],
       [17, 32],
       [15,  7],
       [ 5, 30],
       [25,  4],
       [25, 44],
       [49, 47],
       [10, 26],
       [12, 48],
       [36, 49],
       [ 1, 21],
       [13, 24],
       [15, 18],
       [38, 27],
       [33, 36],
       [36, 24],
       [43, 29],
       [ 4, 20],
       [49,  5],
       [36, 13],
       [12, 18],
       [14,  2],
       [ 9, 29],
       [44, 21],
       [41, 20],
       [15, 33],
       [17, 47],
       [19, 14],
       [20, 13],
       [25, 41

In [94]:
neigh3 = NearestNeighbors(n_neighbors=3)
neigh3.fit(b)

NearestNeighbors(n_neighbors=3)

In [95]:
neigh5 = NearestNeighbors(n_neighbors=5)
neigh5.fit(b)

NearestNeighbors()

In [96]:
neigh7 = NearestNeighbors(n_neighbors=7)
neigh7.fit(b)

NearestNeighbors(n_neighbors=7)

In [97]:
X = np.random.randint(0,50,size=20).reshape(10,2)
#new_b = np.random.randint(0,50,size=10).reshape(-1,1)

In [98]:
X

array([[35,  9],
       [ 4, 35],
       [44, 21],
       [25, 36],
       [36,  6],
       [26,  8],
       [17, 14],
       [ 8, 26],
       [ 5, 16],
       [37,  6]])

In [99]:
#for i in 
z=neigh3.kneighbors(X,n_neighbors=1,return_distance=False)

In [100]:
z

array([[ 71],
       [212],
       [ 52],
       [152],
       [199],
       [ 20],
       [ 56],
       [ 60],
       [163],
       [239]], dtype=int64)

In [101]:
list_z=[]

In [102]:
for i in z:
    for j in i:
        list_z.append(j)
        

In [103]:
list_z

[71, 212, 52, 152, 199, 20, 56, 60, 163, 239]

In [104]:
list_X=[]

In [105]:
for i in X:
    list_X.append(list(i))

In [106]:
list_X

[[35, 9],
 [4, 35],
 [44, 21],
 [25, 36],
 [36, 6],
 [26, 8],
 [17, 14],
 [8, 26],
 [5, 16],
 [37, 6]]

In [107]:
list_a=[]
for i in list_z:
    list_a.append(list(b[i]))

In [108]:
list_a

[[34, 8],
 [4, 36],
 [44, 21],
 [24, 36],
 [35, 7],
 [26, 10],
 [19, 14],
 [8, 27],
 [6, 15],
 [37, 4]]

In [109]:
for i in range(10):
    print("Nearest point to", list_X[i], "is", list_a[i])

Nearest point to [35, 9] is [34, 8]
Nearest point to [4, 35] is [4, 36]
Nearest point to [44, 21] is [44, 21]
Nearest point to [25, 36] is [24, 36]
Nearest point to [36, 6] is [35, 7]
Nearest point to [26, 8] is [26, 10]
Nearest point to [17, 14] is [19, 14]
Nearest point to [8, 26] is [8, 27]
Nearest point to [5, 16] is [6, 15]
Nearest point to [37, 6] is [37, 4]


# Entending the code to n-dimensional space

In [110]:
n=int(input("Enter the number of points"))

Enter the number of points10


In [111]:
X_n = np.random.randint(0,50,size=(2*n)).reshape(n,2)

In [112]:
z=neigh3.kneighbors(X_n,n_neighbors=1,return_distance=False)

In [113]:
z

array([[159],
       [ 92],
       [207],
       [134],
       [ 82],
       [108],
       [156],
       [188],
       [203],
       [237]], dtype=int64)

In [114]:
list_z_n=[]
for i in z:
    for j in i:
        list_z_n.append(j)

In [123]:
list_z_n

[159, 92, 207, 134, 82, 108, 156, 188, 203, 237]

In [115]:
list_x_n=[]
for i in X_n:
    list_x_n.append(list(i))

In [116]:
list_x_n

[[43, 35],
 [29, 12],
 [21, 10],
 [23, 25],
 [27, 13],
 [39, 18],
 [31, 0],
 [7, 26],
 [19, 21],
 [26, 20]]

In [124]:
list_a_n=[]
for i in list_z_n:
    list_a_n.append(list(b[i]))

In [125]:
list_a_n

[[43, 32],
 [29, 12],
 [21, 10],
 [23, 26],
 [28, 13],
 [39, 17],
 [31, 4],
 [6, 27],
 [19, 21],
 [25, 20]]