# Name:Sayan Paul

# Scholar number: 222115107

# Asignment number:4

# Date: 27-Jan-2023

In [217]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [218]:
df=pd.read_excel("datasets_lab4_01.xlsx")

In [219]:
df1=pd.read_excel("datasets_lab4_02.xlsx")

In [220]:
df2=pd.read_excel("datasets_lab4_03.xlsx")

In [221]:
df

x1    y
0   5   99
1   7   86
2   8   87
3   2  100
4  17   86
5   9   87
6   4   94
7  11   78
8  12   77
9   6   86

In [222]:
df1

x1  x2   y
0    2   1  10
1    0   3   3
2   12   8  44
3   14   0  49
4    4   6  18
5   11   4  41
6   19   7  68
7    7  13  32
8    6  14  32
9    5   4  21
10   1  11  14

In [223]:
df2

x1  x2  x3  x4    y
0   21  13  12  15  102
1   16   4   9  18   75
2    0   1   1   7   14
3    9   4   4   5   40
4    5   6   2  16   45
5   13  10   0   7   48
6    8   7  15   3   81
7    1   0   6   2   30
8    9   4   0   9   31
9    7   0   5   9   39
10   6  12  15  14   95
11  19   2   9   6   62
12  12   5   3  17   51
13  11  13  11  14   90
14  15   9  12  11   84

In [224]:
class MeraLR:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train.values,0,1,axis=1)
        
        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    
    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred
    
    def MSE(self,y_test,y_pred):
        squared_err=0
        for i in range(y_test.shape[0]):
            squared_err=squared_err+(y_pred[i]-y_test.values[i])**2
        return squared_err/y_test.shape[0]
    
    def R2_score(self,y_test,y_pred):
        num=0
        dem=0
        for i in range(y_test.shape[0]):
            num=num+(y_pred[i]-y_test.values[i])**2
            dem=dem+(y_pred[i]-y_test.values.mean())**2
        return (1-num/dem)
            
    def SE(self,y_test,y_pred):
        squared_err=0
        for i in range(y_test.shape[0]):
            squared_err=squared_err+(y_pred[i]-y_test.values[i])**2
        return (squared_err/y_test.shape[0])**0.5
    
    #If the variance of errors is highly correlated to the variance of data in a colum, then we can tell that homoscedasticity
    #is not present.
    
    
    

In [225]:
def HCSDCTY(x_train,y_train):
    
    for j in x_train.columns:
        error=[]
        for i in range(x_train.shape[0]):
            error.append(lr.predict(x_train)[i]-y_train.values[i])
        
        print(np.corrcoef(X_train[j].values, np.array(error))[0][1])
        

In [226]:
def HCSDCTY(x_train,y_train):
    
    error=[]
    for i in range(x_train.shape[0]):
        error.append(lr.predict(x_train)[i]-y_train.values[i])
    variances=(error-np.array(error).mean())**2
    homo=variances.max()/variances.min()
    if homo>1.5:
        print("homoscedasdicity is not present")
    else:
        print("homoscedasdicity is present")
        

#### For first dataset

In [227]:
lr=MeraLR()
from sklearn.model_selection import train_test_split 

In [228]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [229]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [230]:
lr.fit(X_train,y_train)

In [231]:
lr.intercept_

104.99558173784985

In [232]:
lr.coef_

array([-2.31516937])

In [233]:
y_pred=lr.predict(X_test)

In [234]:
y_pred

array([65.6377025 , 88.78939617])

In [235]:
lr.MSE(y_test,y_pred)

211.20194516322948

In [236]:
lr.R2_score(y_test,y_pred)

0.0

In [237]:
lr.SE(y_test,y_pred)

14.532788623083647

In [238]:
HCSDCTY(X_train,y_train)

homoscedasdicity is not present


#### For second dataset

In [239]:
lr=MeraLR()

In [240]:
df1.columns

Index(['x1', 'x2', 'y'], dtype='object')

In [241]:
X=df1.iloc[:,0:-1]
y=df1.iloc[:,-1]

In [242]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [243]:
lr.fit(X_train,y_train)

In [244]:
lr.intercept_

3.851485665365061

In [245]:
lr.coef_

array([3.14842037, 0.56037669])

In [246]:
y_pred=lr.predict(X_test)

In [247]:
y_pred

array([19.80742728,  5.53261573, 21.83509428])

In [248]:
lr.MSE(y_test,y_pred)

3.4594394256945944

In [249]:
lr.R2_score(y_test,y_pred)

0.9377841597540836

In [250]:
lr.SE(y_test,y_pred)

1.8599568343632586

In [251]:
HCSDCTY(X_train,y_train)

homoscedasdicity is not present


#### For third dataset

In [252]:
lr=MeraLR()

In [253]:
df2.columns

Index(['x1', 'x2', 'x3', 'x4', 'y'], dtype='object')

In [254]:
X=df2.iloc[:,0:-1]
y=df2.iloc[:,-1]

In [255]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [256]:
lr.fit(X_train,y_train)

In [257]:
lr.intercept_

6.305820067091841

In [258]:
lr.coef_

array([1.03741066, 1.66948166, 3.42919516, 0.78959761])

In [259]:
y_pred=lr.predict(X_test)

In [260]:
y_pred

array([64.95592802, 41.00171544, 42.01415855])

In [261]:
lr.MSE(y_test,y_pred)

20.184695918892995

In [262]:
lr.R2_score(y_test,y_pred)

0.8421082860977922

In [263]:
lr.SE(y_test,y_pred)

4.4927381315733275

In [264]:
HCSDCTY(X_train,y_train)

homoscedasdicity is not present
