# COMMON TERMS

# BAG OF WORDS

In [74]:
import numpy as np
import pandas as pd

In [75]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [76]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [77]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [78]:
bow=cv.fit_transform(df['text'])

In [79]:
print(bow)

  (0, 2)	1
  (0, 3)	1
  (0, 0)	1
  (1, 3)	1
  (1, 0)	2
  (2, 2)	1
  (2, 4)	1
  (2, 1)	1
  (3, 0)	1
  (3, 4)	1
  (3, 1)	1


In [80]:
print(cv.vocabulary_)

#number by the side of the words indicates the indices of the words

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [81]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [82]:
print(bow[1].toarray())

[[2 0 0 1 0]]


In [83]:
cv.transform(['campusx watch and write comment']).toarray()

array([[1, 1, 0, 1, 1]], dtype=int64)

# N-Grams

In [84]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2)) #2,2 indicates there will be bigrams only in the vocabulary

In [86]:
bow=cv.fit_transform(df['text'])

In [87]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]], dtype=int64)

In [88]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [105]:
cv1=CountVectorizer(ngram_range=(1,2)) #1,2 indicates that there will be both bigrams and unigrams in the vocabulary
bow=cv1.fit_transform(df['text'])
print(cv1.vocabulary_)
print(len(cv1.vocabulary_))

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}
11


In [104]:
cv1=CountVectorizer(ngram_range=(3,3)) #3,3 indicates that there will be trigrams in the vocabulary
bow=cv1.fit_transform(df['text'])
print(cv1.vocabulary_)
print(len(cv1.vocabulary_))

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}
4


In [103]:
cv1=CountVectorizer(ngram_range=(2,3)) #2,3 indicates that there will be both bigrams and trigrams in the vocabulary
bow=cv1.fit_transform(df['text'])
print(cv1.vocabulary_)
print(len(cv1.vocabulary_))

{'people watch': 4, 'watch campusx': 8, 'people watch campusx': 5, 'campusx watch': 0, 'campusx watch campusx': 1, 'people write': 6, 'write comment': 9, 'people write comment': 7, 'campusx write': 2, 'campusx write comment': 3}
10


In [102]:
cv1=CountVectorizer(ngram_range=(4,4)) #4,4 indicates that there will be both only quadgrams in the vocabulary.
bow=cv1.fit_transform(df['text'])
print(cv1.vocabulary_)

#here vocabulary is not forming since none of the documents contains 4 words

ValueError: empty vocabulary; perhaps the documents only contain stop words

# TF-IDF

In [107]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text'])

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [108]:
tfidf.fit_transform(df['text']).toarray() #It is being converted to array because tfidf.fit_transfrom returns sparse matrix

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [110]:
print(tfidf.idf_) #idf values are constant for every term
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
