In [2]:

import numpy as np

In [3]:
a=np.array([15,14,13,50,100,56])

In [4]:
a.mean()

41.333333333333336

In [10]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [6]:
np.mean(a)

41.333333333333336

In [7]:
np.median(a)

32.5

In [11]:
a=np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [12]:
np.median(a) #finds the median of all data present in the matrix

4.0

In [13]:
np.median(a,axis=0) #find the median columnwise # Here axis=0 indicates columns

array([3., 4., 5.])

In [15]:
np.median(a,axis=1) #find the median rowwise. #axis=1 indiactes rows

array([5., 4., 4.])

In [16]:
np.mean(a,axis=1) #along rows

array([5., 5., 5.])

In [17]:
np.mean(a,axis=0) #along columns

array([4.33333333, 5.        , 5.66666667])

In [18]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [19]:
np.var(a)

5.333333333333333

In [20]:
np.var(a,axis=0) #columnwise

array([6.88888889, 2.        , 6.22222222])

In [21]:
np.std(a)

2.309401076758503

In [22]:
np.std(a,axis=1) #rowwise

array([1.63299316, 2.1602469 , 2.94392029])

In [23]:
round(np.std(a),2) #round off the standard deviation to two decimal values.

2.31

In [25]:
round(np.std(a),2)

2.31

In [26]:
Range=np.max(a)-np.min(a)
Range

7

In [27]:
import pandas as pd

In [28]:
data=pd.read_csv('president_heights.csv')
data

order                    name  height
0       1       George Washington     189
1       2              John Adams     170
2       3        Thomas Jefferson     189
3       4           James Madison     163
4       5            James Monroe     183
5       6       John Quincy Adams     171
6       7          Andrew Jackson     185
7       8        Martin Van Buren     168
8       9  William Henry Harrison     173
9      10              John Tyler     183
10     11           James K. Polk     173
11     12          Zachary Taylor     173
12     13        Millard Fillmore     175
13     14         Franklin Pierce     178
14     15          James Buchanan     183
15     16         Abraham Lincoln     193
16     17          Andrew Johnson     178
17     18        Ulysses S. Grant     173
18     19     Rutherford B. Hayes     174
19     20       James A. Garfield     183
20     21       Chester A. Arthur     183
21     23       Benjamin Harrison     168
22     25        William McKinley     170
23     26      Theodore Roosevelt     178
24     27     William Howard Taft     182
25     28          Woodrow Wilson     180
26     29       Warren G. Harding     183
27     30         Calvin Coolidge     178
28     31          Herbert Hoover     182
29     32   Franklin D. Roosevelt     188
30     33         Harry S. Truman     175
31     34    Dwight D. Eisenhower     179
32     35         John F. Kennedy     183
33     36       Lyndon B. Johnson     193
34     37           Richard Nixon     182
35     38             Gerald Ford     183
36     39            Jimmy Carter     177
37     40           Ronald Reagan     185
38     41       George H. W. Bush     188
39     42            Bill Clinton     188
40     43          George W. Bush     182
41     44            Barack Obama     185

In [30]:
heights=data['height']
heights

0     189
1     170
2     189
3     163
4     183
5     171
6     185
7     168
8     173
9     183
10    173
11    173
12    175
13    178
14    183
15    193
16    178
17    173
18    174
19    183
20    183
21    168
22    170
23    178
24    182
25    180
26    183
27    178
28    182
29    188
30    175
31    179
32    183
33    193
34    182
35    183
36    177
37    185
38    188
39    188
40    182
41    185
Name: height, dtype: int64

In [31]:
np.mean(data['height'])

179.73809523809524

In [32]:
np.median(data['height'])

182.0

In [33]:
np.std(data['height'])

6.931843442745893

In [34]:
np.max(data['height'])

193

In [40]:
#find the 25 th percentile
m=np.percentile(data['height'],25)

In [41]:
#median is the 50 th percentile
np.percentile(data['height'],50)

182.0

In [42]:
#finding the 75th percentile
n=np.percentile(data['height'],75)

In [43]:
#difference between 75th percentile and 25th percentile is the interquartile range
m-n

-8.75

In [44]:
import matplotlib.pyplot as plt