In [1]:
import pandas as pd
import numpy as np

In [2]:
a=np.array([43,54,56,61,62,66,68,69,69,70,71,72,77,78,79,85,87,88,89,93,95,96,98,99,99])

In [3]:
a

array([43, 54, 56, 61, 62, 66, 68, 69, 69, 70, 71, 72, 77, 78, 79, 85, 87,
       88, 89, 93, 95, 96, 98, 99, 99])

In [4]:
np.percentile(a,60)

81.39999999999999

In [5]:
np.percentile(a,50)

77.0

In [6]:
np.percentile(a,25)

68.0

In [7]:
data=pd.read_csv('president_heights.csv')
data

order                    name  height
0       1       George Washington     189
1       2              John Adams     170
2       3        Thomas Jefferson     189
3       4           James Madison     163
4       5            James Monroe     183
5       6       John Quincy Adams     171
6       7          Andrew Jackson     185
7       8        Martin Van Buren     168
8       9  William Henry Harrison     173
9      10              John Tyler     183
10     11           James K. Polk     173
11     12          Zachary Taylor     173
12     13        Millard Fillmore     175
13     14         Franklin Pierce     178
14     15          James Buchanan     183
15     16         Abraham Lincoln     193
16     17          Andrew Johnson     178
17     18        Ulysses S. Grant     173
18     19     Rutherford B. Hayes     174
19     20       James A. Garfield     183
20     21       Chester A. Arthur     183
21     23       Benjamin Harrison     168
22     25        William McKinley     170
23     26      Theodore Roosevelt     178
24     27     William Howard Taft     182
25     28          Woodrow Wilson     180
26     29       Warren G. Harding     183
27     30         Calvin Coolidge     178
28     31          Herbert Hoover     182
29     32   Franklin D. Roosevelt     188
30     33         Harry S. Truman     175
31     34    Dwight D. Eisenhower     179
32     35         John F. Kennedy     183
33     36       Lyndon B. Johnson     193
34     37           Richard Nixon     182
35     38             Gerald Ford     183
36     39            Jimmy Carter     177
37     40           Ronald Reagan     185
38     41       George H. W. Bush     188
39     42            Bill Clinton     188
40     43          George W. Bush     182
41     44            Barack Obama     185

In [8]:
np.percentile(data['height'],25)

174.25

In [9]:
np.percentile(data['height'],50) #median is the 50 th percentile

182.0

In [10]:
np.percentile(data['height'],75)

183.0

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns

# Scipy- Scientific python library

In [13]:
import scipy
import warnings
warnings.filterwarnings('ignore')

In [14]:
scipy.__version__

'1.6.2'

In [16]:
a

array([43, 54, 56, 61, 62, 66, 68, 69, 69, 70, 71, 72, 77, 78, 79, 85, 87,
       88, 89, 93, 95, 96, 98, 99, 99])

In [15]:
scipy.mean(a)

76.96

In [17]:
scipy.median(a)

77.0

In [18]:
round(scipy.var(a),2) #round off to 2 decimal places

233.24

In [19]:
round(scipy.std(a),2)

15.27

# Mode function

In [20]:
scipy.mode(a)

AttributeError: module 'scipy' has no attribute 'mode'

In [21]:
import scipy.stats as st

In [23]:
b=np.array([[1,3,4,2,2,7],[5,2,2,1,4,1],[3,3,2,2,1,1]])
b

array([[1, 3, 4, 2, 2, 7],
       [5, 2, 2, 1, 4, 1],
       [3, 3, 2, 2, 1, 1]])

In [25]:
mode=st.mode(b)
mode

ModeResult(mode=array([[1, 3, 2, 2, 1, 1]]), count=array([[1, 2, 2, 2, 1, 2]]))

In [26]:
import pandas as pd
df=pd.read_csv('student_marks.csv')
df

Unnamed: 0 Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0       John      M  05-04-1988     55       45         56       87       21   
1     Suresh      M  04-05-1987     75       96         78       64       90   
2     Ramesh      M  25-05-1989     25       54         89       76       95   
3    Jessica      F  12-08-1990     78       96         86       63       54   
4   Jennifer      F  02-09-1989     58       96         78       46       96   
5       Annu      F  05-04-1988     45       87         52       89       55   
6      pooja      F  04-05-1987     55       64         61       58       75   
7     Ritesh      M  25-05-1989     54       76         87       56       25   
8      Farha      F  12-08-1990     55       63         89       75       78   
9     Mukesh      M  02-09-1989     96       46         77       83       58   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53  
5         89       87      52  
6         58       64      61  
7         56       76      87  
8         75       63      89  
9         83       46      77

In [27]:
df['Maths'].mean()

59.6

In [32]:
df['Chemistry'].mode()

0    78
1    89
dtype: int64

In [30]:
df.describe()

Maths    Physics  Chemistry    English    Biology  Economics  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   59.600000  72.300000  75.300000  69.700000  64.700000  72.700000   
std    19.460501  20.661559  14.000397  14.453373  26.998148  14.629119   
min    25.000000  45.000000  52.000000  46.000000  21.000000  52.000000   
25%    54.250000  56.250000  65.000000  59.250000  54.250000  58.750000   
50%    55.000000  70.000000  78.000000  69.500000  66.500000  76.000000   
75%    70.750000  93.750000  86.750000  81.250000  87.000000  86.000000   
max    96.000000  96.000000  89.000000  89.000000  96.000000  89.000000   

         History   Civics  
count  10.000000  10.0000  
mean   69.700000  60.5000  
std    14.453373  25.3432  
min    46.000000   2.0000  
25%    59.250000  52.2500  
50%    69.500000  63.0000  
75%    81.250000  76.2500  
max    89.000000  89.0000

In [33]:
from scipy.stats import percentileofscore as psc

In [34]:
psc(df['Maths'],25)

10.0

In [35]:
scipy.stats.percentileofscore(df['Chemistry'],75)

30.0

In [39]:
from scipy.stats import percentileofscore

In [40]:
percentileofscore(df['Economics'],60)

30.0

In [44]:
max_m=df['Maths'].max()
max_m

96

In [45]:
min_m=df['Maths'].min()
min_m

25

In [47]:
range=max_m-min_m
range

71

In [49]:
df['English'].quantile(.25)

59.25

In [50]:
df['Biology'].quantile(0.50)

66.5